# Generated by Django 5.0.6 on 2024-07-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_tournamentresults_results_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='age_limit',
            field=models.IntegerField(default=0),
        ),
    ]
