# Generated by Django 5.0.6 on 2024-07-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_tournament_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='age_limit',
            field=models.IntegerField(),
        ),
    ]
