# Generated by Django 5.0.6 on 2024-07-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_tournament_age_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
