# Generated by Django 5.0.6 on 2024-07-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_tournament_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(default='', max_length=900),
        ),
        migrations.AddField(
            model_name='tournament',
            name='venue',
            field=models.CharField(default='Prince Edward High', max_length=55),
        ),
    ]
