# Generated by Django 5.0.6 on 2024-07-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_tournament_end_date_tournament_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='venue',
            field=models.CharField(max_length=55),
        ),
    ]
