# Generated by Django 5.0.6 on 2024-07-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_tournament_description_alter_tournament_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=800)),
                ('youtube_url', models.URLField()),
                ('cover_image', models.ImageField(upload_to='gallery')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
