# Generated by Django 5.0.6 on 2024-07-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_schoolprofile_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
