# Generated by Django 5.0.6 on 2024-07-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_rename_name_player_first_name_player_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
