# Generated by Django 5.0.6 on 2024-07-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_player_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cell',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='', max_length=255),
        ),
    ]
