# Generated by Django 5.0.6 on 2024-07-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_player_cell_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cell',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
