# Generated by Django 5.0.6 on 2024-07-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_player_cell_alter_player_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='picture',
            new_name='passport_photo',
        ),
        migrations.AddField(
            model_name='player',
            name='birth_certificate_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='guardian_contact',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='guardian_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='guardian_relationship',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='middle_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='present_school',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_school',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='year_enrolled',
            field=models.CharField(default='', max_length=255),
        ),
    ]
