# Generated by Django 5.0.6 on 2024-07-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_rename_picture_player_passport_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='birth_certificate_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='guardian_contact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='guardian_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='guardian_relationship',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='middle_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='present_school',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='previous_school',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='year_enrolled',
            field=models.CharField(max_length=255),
        ),
    ]
