# Generated by Django 5.0.6 on 2024-07-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_alter_player_birth_certificate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='middle_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
